version: '3.5'
services:
  nodejs-sample:
    build: .
    ports:
      - '8888:8888'
    depends_on:
      - db
      - consul
    networks:
      - app-network
    environment:
      - NODE_ENV=prod
  db:
    image: mongo:5.0.14
    ports:
      - '27018:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
    networks:
      - app-network
  consul:
    image: consul:1.15.2
    ports:
      - '8501:8500'
    volumes:
      - ./docker/data/consul/data:/consul/data
      - ./docker/data/consul/config:/consul/config
      - ./resources/consul:/resources/consul
    networks:
      - app-network
    command:
      - sh
      - -c
      - |
        consul agent -server -ui -bind 0.0.0.0 -client 0.0.0.0 -data-dir /consul/data -config-dir /consul/config -bootstrap -datacenter docker &
        consul_pid=$!
        sleep 5
        consul kv import -http-addr=http://0.0.0.0:8500 @/resources/consul/consul-config-kv.json
        wait $consul_pid

networks:
  app-network:
